# Site settings
title:       Blog of Anders Nissen
email:       andnis@gmail.com
author:      Anders Nissen
description: "Rambling of a spare-time indie game dev."
baseurl:     "/blog"
url:         "http://andersnissen.com"

# Google analytics
google_analytics: UA-32783311-3

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:   andersnissensblog

# Social icons
github_username:    anissen
stackoverflow_id:
twitter_username:   andershnissen
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
