# Site settings
title:       Blog of Anders Nissen
email:       andnis@gmail.com
author:      Anders Nissen
description: "Rambling of a spare-time indie game dev."
baseurl:     "/blog"
url:         "http://andersnissen.com"

# Google analytics
google_analytics: UA-32783311-3

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:   andersnissensblog

# Social icons
show_social_icons:  true
github_username:    anissen
stackoverflow_id:
twitter_username:   andershnissen
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
